[[redirects]]
  from = "/payment-success.html"
  to = "/.netlify/functions/payment-redirect"
  status = 200
  force = true

[[redirects]]
  from = "/payment-failure.html"
  to = "/.netlify/functions/payment-redirect"
  status = 200
  force = true
